#!/usr/bin/env python3
"""Write epg/guide.channels.xml: the list of channels iptv-org's grabber
fetches TV-guide data for.

It combines:
- epg/manual.channels.xml: hand-picked sources (SVT, Viasat… via allente.se)
- every Pluto TV channel from config.json's guideCountries. Our Pluto stream
  URLs contain Pluto's channel id (jmp2.uk/plu-<id>), which is the id
  Pluto's guide uses, so these are matched automatically.

Run: python3 scripts/build_epg_channels.py
"""
import json
import os
import re
from xml.sax.saxutils import escape

ROOT = os.path.join(os.path.dirname(__file__), "..")
PLUTO_ID = re.compile(r"jmp2\.uk/plu-([0-9a-f]{24})")


def main():
    with open(os.path.join(ROOT, "config.json"), encoding="utf-8") as f:
        config = json.load(f)
    with open(os.path.join(ROOT, "data", "channels.json"), encoding="utf-8") as f:
        channels = json.load(f)["channels"]
    with open(os.path.join(ROOT, "epg", "manual.channels.xml"), encoding="utf-8") as f:
        manual = f.read()

    manual_lines = re.findall(r"^\s*<channel .*</channel>\s*$", manual, re.M)
    covered = set(re.findall(r'xmltv_id="([^"]+)"', manual))

    countries = config.get("guideCountries", [])
    auto = []
    for ch in channels:
        if ch["c"] not in countries or ch["i"] in covered:
            continue
        m = PLUTO_ID.search(ch["s"][0]["u"])
        if m:
            auto.append(
                f'  <channel site="pluto.tv" site_id="{m.group(1)}" lang="en" '
                f'xmltv_id="{ch["i"]}">{escape(ch["n"])}</channel>'
            )
            covered.add(ch["i"])

    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           "<!-- Generated by scripts/build_epg_channels.py; edit manual.channels.xml instead. -->",
           "<channels>"]
    out += [line.rstrip() for line in manual_lines] + auto + ["</channels>", ""]
    with open(os.path.join(ROOT, "epg", "guide.channels.xml"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"Wrote {len(manual_lines)} manual + {len(auto)} Pluto TV guide channels "
          f"({', '.join(countries)}) to epg/guide.channels.xml")


if __name__ == "__main__":
    main()
